spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**
  datasource:
     driver-class-name: org.h2.Driver
     username: admin
     password: admin@123
     url: jdbc:h2:file:/home/tubel/db/assignment_upload_db1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  thymeleaf:
    mode: HTML
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html

    thymeleaf.extras.springsecurity5.enabled: true

